runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6

handlers:
- url: /content
  static_dir: content
- url: /tasks/update
  script: instagram.app
  login: admin
- url: /.*
  script: instagram.app

